### ISSUE TITLE
Show support for Nova version 3 or 4

### ISSUE THREAD

**Issue by timbertens** [tighten/novapackages#196]
Now that Nova 4 is out in the wild, I believe it is useful to add some metadata to each packages to mark its support for version 3 or 4
Also it would be nice if the packages could be filtered on their version support

**Comment by RhysLees** [comment]
Just about to ask this

**Comment by edanisko** [comment]
up

**Comment by marcusmoore** [comment]
Good suggestion @timbertens. I'll explore this tomorrow 😄

**Comment by marcusmoore** [comment]
Did a little exploring today and yeah! We can support both Nova version support information on the sidebar of packages and adding a filter to the home page to easily find v4 supported packages.

I think we can use the ["Getting package data"](https://packagist.org/apidoc#get-package-data) endpoint that Packagist provides to determine if a package supports v4 by checking the releases’ `require` field for `laravel/nova` with a "`4`" entry (ie: `"^4.0"`).

One gotcha is that not all packages explicitly have a `laravel/nova` entry in `require`.

I'll start work on this late next week unless someone else wants to take a swing at it 😄

**Comment by RhysLees** [comment]
> Did a little exploring today and yeah! We can support both Nova version support information on the sidebar of packages and adding a filter to the home page to easily find v4 supported packages.
> 
> I think we can use the ["Getting package data"](https://packagist.org/apidoc#get-package-data) endpoint that Packagist provides to determine if a package supports v4 by checking the releases’ `require` field for `laravel/nova` with a "`4`" entry (ie: `"^4.0"`).
> 
> One gotcha is that not all packages explicitly have a `laravel/nova` entry in `require`.
> 
> I'll start work on this late next week unless someone else wants to take a swing at it 😄

Im just having a crack at it now

![image](https://user-images.githubusercontent.com/43909932/164756645-015e22dc-cb73-472d-9cf5-882d6a0077ee.png)

**Comment by marcusmoore** [comment]
Thanks @RhysLees! Totally ok with you diving into this 😄 

Some questions, thoughts, and comments:

I think something we should consider is that different versions of the package can supported different versions of Nova. For example, [`maatwebsite/laravel-nova-excel`](https://packagist.org/packages/maatwebsite/laravel-nova-excel#1.3.0) `1.3.0` supports v4 but `1.2.10` have `laravel/nova` listed as `*`. Should we tell users that v4 is supported in `1.3.0` and up in some way or just tell them it has v4 compatibility available and let composer handle it for them when they install? I think the latter is better? 

I like your screenshot of the individual package page 👍🏾 
![individual package page](https://user-images.githubusercontent.com/1141514/164759505-52606666-9d97-43f6-b0b7-b264d57c7143.png)

For the home page, I'm not sure displaying the nova version on each card is a good use of space. I was thinking we could do something like this where clicking the link filters the packages by `tag=v4` or something similar:
![home page](https://user-images.githubusercontent.com/1141514/164761507-0e0b23d1-c967-48bc-a892-7b58deab1982.png)

Let me know what you think and thanks again 😄

**Comment by RhysLees** [comment]
@marcusmoore I agree, I think it would be best to let the composer handle the version rather than specifying the version that supports it

In regards to the home page, I'm planning on adding the filters for nova 4 but I do believe maybe we should have the tag if it has the latest version support. Maybe we add into config or env what the current major version is i.e 3,4,5 then show an icon or banner on the card if a version of the package supports the latest version on nova? maybe that could be a good compromise?

Another thing I ran into with the seeded data at least, is some of the packages only require nova in `require-dev` and I'm not sure of the best way to handle this. Also if it is in neither `require` or `require-dev`.

If not in `require` but is in `require-dev`
- Merge `require` and `require-dev`
or
- Return null 

If not in `require` or `require-dev`
- Assume nova 4 support
or
- Return null

In regards to  
> [maatwebsite/laravel-nova-excel](https://packagist.org/packages/maatwebsite/laravel-nova-excel#1.3.0) 1.3.0 supports v4 but 1.2.10 have laravel/nova listed as *. Should we tell users that v4 is supported in 1.3.0

if the `*` is used then it means it can support any version so do we assume it has Nova 4 support or instead returns null as we dont know for certain, especially if a new nova version has just been released?

**Comment by marcusmoore** [comment]
@RhysLees 

> I agree, I think it would be best to let the composer handle the version rather than specifying the version that supports it

👍🏾 

> In regards to the home page, I'm planning on adding the filters for nova 4 but I do believe maybe we should have the tag if it has the latest version support. 

This is a good point. Having a visual indicator on the card would be helpful when a user is using the search box and visually scanning the results. 

> Maybe we add into config or env what the current major version is i.e 3,4,5 then show an icon or banner on the card if a version of the package supports the latest version on nova? maybe that could be a good compromise?

A config entry in a new configuration file (something like `custom`) reading from an environmental variable sounds good to me.

I like the idea of an non-intrusive icon and/or piece of text that, ideally, doesn't raise the height of the bottom of the card where the author is:

![card](https://user-images.githubusercontent.com/1141514/164778226-93a4b309-02c0-4972-b11a-d0321dc7a4ab.png)

I'm not sure what a good option is that conveys "Works with Nova 4" but doesn't include all of the words. Let me know what you're thinking.

> if the * is used then it means it can support any version so do we assume it has Nova 4 support or instead returns null as we dont know for certain, especially if a new nova version has just been released?

I think your question here points us in the right direction for the paragraph above it. I don't think we should assume the package works with Nova 4 unless it explicitly declares it. I think that would be better for users as well because displaying packages as having Nova 4 support without the package declaring that could cause people to install a package and then get frustrated when they find out it doesn't actually work with Nova.

Thanks for all of your thoughtfulness 😄

**Comment by RhysLees** [comment]
> 

Thanks for shedding some light on the issues I had.

# Card shows the latest version support

Just messing around with the styling and what I have as seen in the image below doesn't change the size of the box footer all have 57px height.

![image](https://user-images.githubusercontent.com/43909932/164781367-80720748-3427-44cc-a65b-58be05120dd2.png)

## Another option would be this "corner tag"

![image](https://user-images.githubusercontent.com/43909932/164785011-ec8e659a-1334-4d6a-8006-5aa14f473dab.png)

## With a shorter name

![image](https://user-images.githubusercontent.com/43909932/164785403-be6f4b0c-e998-4f11-8d27-79d82f9a37a9.png)


## With an even shorter name

![image](https://user-images.githubusercontent.com/43909932/164785135-5e51281f-2e45-4ad4-9135-696ee7ace37e.png)

**Comment by marcusmoore** [comment]
> the image below doesn't change the size of the box footer all have 57px height

😅 my eyes were playing tricks on me.

👍🏾  I like the corner tag with `Nova 4 Support`.

I see you've opened a PR so we can continue the conversation there 😄

**Comment by RhysLees** [comment]
> > the image below doesn't change the size of the box footer all have 57px height
> 
> 😅 my eyes were playing tricks on me.
> 
> 👍🏾 I like the corner tag with `Nova 4 Support`.
> 
> I see you've opened a PR so we can continue the conversation there 😄

Sure thing 👌
