### ISSUE TITLE
Bring back infinite loading?

### ISSUE THREAD

**Issue by patrickdeamorim** [tighten/novapackages#39]
It's really a pain having to click next-next-next when you just want to browse through packages.
With 83 pages, it makes it really hard to browse and discover something new.

**Comment by mattstauffer** [comment]
We've talked about potentially moving to infinite scroll, but for now, you can at least use the keyboard shortcuts (left and right) to move through it more quickly

**Comment by trafficfox** [comment]
Understand. Didn't know about using the keyboard, so that helps a lot.
I'd say that either this or infinite scroll works, since the overall site itself is so great and this being just a detail.

One argument I'll make for infinite scroll though is that it's somewhat easier, as your eyes goes left-right in a constant downwards motion, as opposed to finishing looking at the bottom right, then your eyes having to jump back to the top left.
